<?php

$array = array(
    array(1, 'Smack', 'Twisted - Week 1', 1452808800, '<p>Huge night of House & Club Bangers upstairs, and the legendary DJ Firstborn down in the LED Basement serving up the best R&B and Hip Hop.</p><p>DRINKS:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Bottles - £1.50</p>',  0, '1551421391816026', 'CV32 5PJ', 'Smack'),
	array(2, 'JägerMonster', 'JägerMonster - Week 1', 1452898800, '<p>For 5 years JagerMonster Warwick has been the biggest student night in Leamington Spa!<br/>Drinks:<br/>Vodka Mixers: £1.50<br/>JagerMonster: £1.50<br/>Shots: £1.50</p>',  0, '1545864322405849', 'CV31 3NF', 'Neon'),
	array(3, 'Smack', 'FLY - Week 2', 1453413600, '<p>The return of Smack\'s urban music night, bringing you the best in Hip Hop, R&B, House and Trap all night long. </p><p>Drinks:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Selected Bottles - £1.50</p>',  0, '475973449252881', 'CV32 5PJ', 'Smack'),
	array(4, 'JägerMonster', 'JägerMonster - Week 2', 1453503600, '<p>For 5 years JagerMonster Warwick has been the biggest student night in Leamington Spa!</p><p>Drinks:<br/>Vodka Mixers: £1.50<br/>JagerMonster: £1.50<br/>Shots: £1.50</p>',  0, '1650985658488226', 'CV31 3NF', 'Neon'),
	array(5, 'Smack', 'Twisted - Week 3', 1454018400, '<p>Huge night of House & Club Bangers upstairs, and the legendary DJ Firstborn down in the LED Basement serving up the best R&B and Hip Hop.</p><p>DRINKS:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Bottles - £1.50</p>',  0, '1011823892190308', 'CV32 5PJ', 'Smack'),
	array(6, 'Kasbah', 'KINKY - Week 3', 1454104800, '<p>The biggest Student Night Coventry has ever seen.<br/>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room: A mix of Party – Charty – Dance – Pop<br/>Side Room: Live Music followed by Indie – Alternative – Rock<br/>Globe Bar: Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(7, 'JägerMonster', 'JägerMonster - Week 3', 1454108400, '<p>For 5 years JagerMonster Warwick has been the biggest student night in Leamington Spa!</p><p>Drinks:<br/>Vodka Mixers: £1.50<br/>JagerMonster: £1.50<br/>Shots: £1.50</p>',  0, '1544711475839402', 'CV31 3NF', 'Neon'),
	array(8, 'Kasbah', 'BUBBLELUV - Week 4', 1454367600, '<p>The biggest Student Night Coventry has ever seen. <br/>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room – Chart / R’N’B / Dance / POPTASTIC classics<br/>Left Wing – Up n Coming Live Music / Alternative Disco afterwards<br/>Globe Bar – Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(9, 'Smack', 'FLY - Week 4', 1454623200, '<p>The return of Smack\'s urban music night, bringing you the best in Hip Hop, R&B, House and Trap all night long. </p><p>Drinks:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Selected Bottles - £1.50</p>',  0, '1685267288379259', 'CV32 5PJ', 'Smack'),
	array(10, 'JägerMonster', 'JägerMonster - Week 4', 1454713200, '<p>For 5 years JagerMonster Warwick has been the biggest student night in Leamington Spa!</p><p>Drinks:<br/>Vodka Mixers: £1.50<br/>JagerMonster: £1.50<br/>Shots: £1.50</p>',  0, '1683015268604465', 'CV31 3NF', 'Neon'),
	array(11, 'JägerMonster', 'Saints & Sinners Barcrawl - Week 5', 1455220800, '<p>The big mid-term Barcrawl ending at SMACK for the first time! Saints and Sinners is the theme...what will you be? On which side do you fall...</p><p>With the usual incredible drinks deals from £1, we\'ll be taking you through 6 of Leamington\'s finest watering holes before ending the night at Smack.</p><p>Tickets include EXCLUSIVE drinks deals in all bars, AND EXCLUSIVE Q-JUMP entry into Smack!</p>',  1, '614104018738364', 'CV32 5PJ', 'Smack'),
	array(12, 'Kasbah', 'KINKY - Week 4', 1454709600, '<p>The biggest Student Night Coventry has ever seen. <br/>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room: A mix of Party – Charty – Dance – Pop<br/>Side Room: Live Music followed by Indie – Alternative – Rock<br/>Globe Bar: Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(13, 'Kasbah', 'BUBBLELUV - Week 5', 1454972400, '<p>The biggest Student Night Coventry has ever seen. <br/>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room – Chart / R’N’B / Dance / POPTASTIC classics<br/>Left Wing – Up n Coming Live Music / Alternative Disco afterwards<br/>Globe Bar – Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(14, 'Kasbah', 'KINKY - Week 5', 1455314400, '<p>The biggest Student Night Coventry has ever seen. <br/>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room: A mix of Party – Charty – Dance – Pop<br/>Side Room: Live Music followed by Indie – Alternative – Rock<br/>Globe Bar: Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(15, 'JägerMonster', 'JägerMonster - Week 5', 1455318000, '<p>For 5 years JagerMonster Warwick has been the biggest student night in Leamington Spa!</p><p>Drinks:<br/>Vodka Mixers: £1.50<br/>JagerMonster: £1.50<br/>Shots: £1.50</p>',  0, '780363212065932', 'CV31 3NF', 'Neon'),
	array(16, 'Smack', 'Twisted - Week 5', 1455231600, '<p>Huge night of House & Club Bangers upstairs, and the legendary DJ Firstborn down in the LED Basement serving up the best R&B and Hip Hop.</p><p>DRINKS:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Bottles - £1.50</p>',  0, '556671797834455', 'CV32 5PJ', 'Smack'),
	array(17, 'Kasbah', 'BUBBLELUV - Week 6', 1455577200, '<p>The biggest Student Night Coventry has ever seen. <br/>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room – Chart / R’N’B / Dance / POPTASTIC classics<br/>Left Wing – Up n Coming Live Music / Alternative Disco afterwards<br/>Globe Bar – Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(18, 'Smack', 'FLY - Week 6', 1455836400, '<p>The return of Smack\'s urban music night, bringing you the best in Hip Hop, R&B, House and Trap all night long. </p><p>Drinks:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Selected Bottles - £1.50</p>',  0, '652394984899767', 'CV32 5PJ', 'Smack'),
	array(19, 'Kasbah', 'KINKY - Week 6', 1455919200, '<p>The biggest Student Night Coventry has ever seen. <br/>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room: A mix of Party – Charty – Dance – Pop<br/>Side Room: Live Music followed by Indie – Alternative – Rock<br/>Globe Bar: Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(20, 'JägerMonster', 'JägerMonster - Week 6', 1455922800, '<p>For 5 years JagerMonster Warwick has been the biggest student night in Leamington Spa!</p><p>Drinks:<br/>Vodka Mixers: £1.50<br/>JagerMonster: £1.50<br/>Shots: £1.50</p>',  0, '1119920984720055', 'CV31 3NF', 'Neon'),
	array(21, 'Kasbah', 'BUBBLELUV - Week 7', 1456182000, '<p>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room – Chart / R’N’B / Dance / POPTASTIC classics<br/>Left Wing – Up n Coming Live Music / Alternative Disco afterwards<br/>Globe Bar – Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(22, 'Smack', 'Twisted - Week 7', 1456441200, '<p>Huge night of House & Club Bangers upstairs, and the legendary DJ Firstborn down in the LED Basement serving up the best R&B and Hip Hop.</p><p>DRINKS:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Bottles - £1.50</p>',  0, '450356638493143', 'CV32 5PJ', 'Smack'),
	array(23, 'Kasbah', 'KINKY - Week 7', 1456524000, '<p>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room: A mix of Party – Charty – Dance – Pop<br/>Side Room: Live Music followed by Indie – Alternative – Rock<br/>Globe Bar: Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(24, 'JägerMonster', 'JägerMonster - Week 7', 1456527600, '<p>For 5 years JagerMonster Warwick has been the biggest student night in Leamington Spa!</p><p>Drinks:<br/>Vodka Mixers: £1.50<br/>JagerMonster: £1.50<br/>Shots: £1.50</p>',  0, '735976009871056', 'CV31 3NF', 'Neon'),
	array(25, 'Warwick HistSoc', 'Switch it Up', 1456527600, '<p>The Assembly is celebrating two years since the inaugural Switch took place, pulling in a stellar line up consisting of:</p><p>- Kahn<br/>- Sir Spyro<br/>- Amy Becker<br/>- Jammz</p><p>£1 of each ticket going towards our partner charity Rays of Sunshine. </p>',  1, '492200467654952', 'CV31 3NF', 'Leamington Assembly'),
	array(26, 'Warwick Lithuanian Society', 'Kujeliu koncertas Warwick\'o universitete', 1456945200, '<p>K&#363;jeliai is a Lithuanian band renowned for their catchy folk music with a modern twist. Their truly unique songs incorporate a wide range of traditional folk instruments including whistles, harmonicas, mandolins and spoons. K&#363;jeliai are visiting Warwick University on the 2nd of March and invite everyone to share their musical passion! The event will also serve as a commemoration of the Day of Restoration of Independence of Lithuania.', 0,  '1687727014842433', 'CV4 7AL', 'PAIS Common Room, Social Sciences'),
	array(27, 'Kasbah', 'BUBBLELUV - Week 8', 1456786800, '<p>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room – Chart / R’N’B / Dance / POPTASTIC classics<br/>Left Wing – Up n Coming Live Music / Alternative Disco afterwards<br/>Globe Bar – Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(28, 'Smack', 'FLY - Week 8', 1457046000, '<p>The return of Smack\'s urban music night, bringing you the best in Hip Hop, R&B, House and Trap all night long.</p>',  0, '199184407104388', 'CV32 5PJ', 'Smack'),
	array(29, 'Kasbah', 'KINKY - Week 8', 1457128800, '<p>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room: A mix of Party – Charty – Dance – Pop<br/>Side Room: Live Music followed by Indie – Alternative – Rock<br/>Globe Bar: Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(30, 'JägerMonster', 'JägerMonster - Week 8', 1457132400, '<p>With an absolutely unbeatable atmosphere, huge tunes from all your favourite genres and the biggest crowd in town... You know where to be!</p><p>Main room featuring the biggest dancefloor classics as well as new music from the world of house and chart remixes.<br/></p>',  1, '244004492608260', 'CV31 3NF', 'Neon'),
	array(31, 'Kasbah', 'BUBBLELUV - Week 9', 1457391600, '<p>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room – Chart / R’N’B / Dance / POPTASTIC classics<br/>Left Wing – Up n Coming Live Music / Alternative Disco afterwards<br/>Globe Bar – Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(32, 'The', 'Legendary Easter Barcrawl', 1458244800, '<p>WRISTBAND - Includes entry into all bars and Neon</p><p>It\'s that time of the year... how the have two terms gone by... the last night of term, the big one, always legendary... and this year we\'ve gone all out. </p><p>The Crawl:<br/>Moo Bar<br/>Saint Bar<br/>Duke<br/>Loose Box<br/>TJs<br/>NEON</p><p>Drinks from £1 with Wristband from all venues!<br/>Fancy Dress prize for Easter Theme<br/>Huge Chocolate Egg GIVEAWAY!</p>',  1, '1668273516756767', 'CV31 3NF', 'Neon'),
	array(33, 'Smack', 'Twisted - Week 9', 1457650800, '<p>Huge night of House & Club Bangers upstairs, and the legendary DJ Firstborn down in the LED Basement serving up the best R&B and Hip Hop.</p><p>DRINKS:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Bottles - £1.50</p>',  0, NULL, 'CV32 5PJ', 'Smack'),
	array(34, 'Kasbah', 'KINKY - Week 9', 1457733600, '<p>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room: A mix of Party – Charty – Dance – Pop<br/>Side Room: Live Music followed by Indie – Alternative – Rock<br/>Globe Bar: Funky House</p>',  0, NULL, 'CV1 5LY', 'Kasbah'),
	array(35, 'JägerMonster', 'JägerMonster - Week 9', 1457737200, '<p>With an absolutely unbeatable atmosphere, huge tunes from all your favourite genres and the biggest crowd in town... You know where to be!</p><p>Main room featuring the biggest dancefloor classics as well as new music from the world of house and chart remixes. <br/></p>',  0, NULL, 'CV31 3NF', 'Neon'),
	array(36, 'JägerMonster', 'JägerMonster - Week 10', 1458342000, '<p>With an absolutely unbeatable atmosphere, huge tunes from all your favourite genres and the biggest crowd in town... You know where to be!</p><p>Main room featuring the biggest dancefloor classics as well as new music from the world of house and chart remixes. <br/></p>',  1, NULL, 'CV31 3NF', 'Neon'),
	array(37, 'Internet,', 'Participation and Society: Opportunities for the Global South', 0, '<p>The Warwick Mexican Society in collaboration with the Department of Politics and International Studies and the Centre for Multidisciplinary Studies present: &quot;Internet Participation and Society: Opportunities for the Global South&quot;</p><p>The aim of the conference is to foster and encourage research about the Internet and its socio-political impact. By bringing together researchers in the field, it contributes to the critical and informative dialogue on challenges and opportunities of the Internet as a tool of democratization, participation and collective action. Thus, related research can improve the status quo for countries in the global south.</p>',  0, '755323257935579', 'CV4 7AL', 'Helen Martin Studio'),
	array(38, 'Smack', 'FLY - Week 10', 1458255600, '<p>The return of Smack\'s urban music night, bringing you the best in Hip Hop, R&B, House and Trap all night long.</p>',  1, NULL, 'CV32 5PJ', 'Smack'),
	array(39, 'Kasbah', 'KINKY - Week 10', 1458338400, '<p>With a mixture of massive tunes, awesome drink deals & amazing party themes will make every week better than the last!!</p><p>Main Room: A mix of Party – Charty – Dance – Pop<br/>Side Room: Live Music followed by Indie – Alternative – Rock<br/>Globe Bar: Funky House</p>',  1, NULL, 'CV1 5LY', 'Kasbah'),
	array(40, 'JägerMonster', 'JägerMonster - Week 1', 1461967200, '<p>With an absolutely unbeatable atmosphere, huge tunes from all your favourite genres and the biggest crowd in town... You know where to be!</p><p>Main room featuring the biggest dancefloor classics as well as new music from the world of house and chart remixes. <br/></p>',  0, NULL, 'CV31 3NF', 'Neon'),
	array(41, 'Smack', 'Twisted - Week 1', 1461880800, '<p>Huge night of House & Club Bangers upstairs, and the legendary DJ Firstborn down in the LED Basement serving up the best R&B and Hip Hop.</p><p>DRINKS:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Bottles - £1.50</p>',  0, '777623549005825', 'CV32 5PJ', 'Smack'),
	array(42, 'Warwick Histsoc', 'Rock the Kasbah: Histsoc Hits Kasbah, The Finale', 0, '<p>Woooo, you\'ve made it to term 3, congratulations!<br/>With long essays, dissertations and exams all looming in the distance, have a night off. Relax. Destress. Join us as we make our final trip (of Rox and Badock\'s tenure as social secs #endofanera) to Kazzy b</p><p>Pick-up times:<br/>Leamington 10:30pm<br/>Campus 11:00pm</p>',  1, '166650457062380', '', ''),
	array(43, 'JägerMonster', 'JägerMonster - Week 2', 1462572000, '<p>With an absolutely unbeatable atmosphere, huge tunes from all your favourite genres and the biggest crowd in town... You know where to be!</p><p>Main room featuring the biggest dancefloor classics as well as new music from the world of house and chart remixes. <br/></p>',  0, '717405238402673', 'CV31 3NF', 'Neon'),
	array(44, 'Smack', 'FLY - Week 2', 1462485600, '<p>The return of Smack\'s urban music night, bringing you the best in Hip Hop, R&B, House and Trap all night long.</p>',  0, '223707338004740', 'CV32 5PJ', 'Smack'),
	array(45, 'JägerMonster', 'JägerMonster - Week 3', 1463176800, '<p>With an absolutely unbeatable atmosphere, huge tunes from all your favourite genres and the biggest crowd in town... You know where to be!</p><p>Main room featuring the biggest dancefloor classics as well as new music from the world of house and chart remixes. <br/></p>',  0, '', 'CV31 3NF', 'Neon'),
	array(46, 'Smack', 'Twisted - Week 3', 1463090400, '<p>Huge night of House & Club Bangers upstairs, and the legendary DJ Firstborn down in the LED Basement serving up the best R&B and Hip Hop.</p><p>DRINKS:<br/>Vodka Mixers - £1.50<br/>Shots - £1.50<br/>Bottles - £1.50</p>',  0, '', 'CV32 5PJ', 'Smack'),
	array(47, 'Smack', 'FLY - Week 6', 1464908400, '<p>The return of Smack\'s urban music night, bringing you the best in Hip Hop, R&B, House and Trap all night long.',  0, '225093527874757', 'CV32 5PJ', 'Smack')
);

header('Content-Type: text/plain');

foreach($array as $i=>$event){
	$array[$i][3] = gmdate("Y-m-d H:i:s", $event[3]);
	$array[$i][4] = preg_replace("/[\n\r]/","",$event[4]);
}

foreach($array as $event){
	echo '(';
	foreach($event as $prop){
		echo '"'.$prop.'", ';
	}
	echo ')'."\n";
}